---
abstract: 'Create ref/json to show node-edge graph with D3.js '
author:
  - 'Shohei Kameda <shoheik@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.016
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.0, Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-D3
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Graph: 0.94
  JSON: 2.53
  Moo: 1.001000
  perl: v5.6.0
resources:
  bugtracker: https://github.com/shoheik/Graph-D3/issues
  homepage: https://github.com/shoheik/Graph-D3
  repository: https://github.com/shoheik/Graph-D3.git
version: 0.03
